services:
  postgres:
    image: postgres:16
    container_name: app_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: localhubdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    build: .
    container_name: app_backend
    restart: always
    depends_on:
      - postgres
    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: localhubdb
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    command: npm run start
volumes:
  postgres_data:
